# Generated by Django 5.0.4 on 2024-07-27 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_carstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.carstatus', verbose_name='Status'),
        ),
    ]
