# Generated by Django 5.0.4 on 2024-07-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_car_car_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_status',
        ),
        migrations.DeleteModel(
            name='CarStatus',
        ),
    ]
