# Generated by Django 5.0.4 on 2024-07-27 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_car_car_status_delete_carstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuslar',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.carstatus', verbose_name='Status'),
        ),
    ]
