# Generated by Django 5.0.4 on 2024-07-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_carstatus_car_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearchoices',
            name='name',
            field=models.IntegerField(max_length=16),
        ),
    ]
