# Generated by Django 5.0.6 on 2024-07-31 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_isapproved_alter_yearchoices_name_car_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_approved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.isapproved', verbose_name='Tesdiq'),
        ),
    ]
