# Generated by Django 5.0.6 on 2024-07-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_car_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isapproved',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Tesdiq'),
        ),
    ]
