# Generated by Django 5.0.6 on 2024-07-31 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_isapproved_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.isapproved', verbose_name='Tesdiq'),
        ),
    ]
