# Generated by Django 5.0.6 on 2024-08-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_car_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecar',
            name='image',
            field=models.CharField(max_length=255, verbose_name='Şəkil'),
        ),
    ]
