# Generated by Django 5.0.6 on 2024-08-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_imagecar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecar',
            name='image',
            field=models.ImageField(upload_to='user/img_cars', verbose_name='Şəkil'),
        ),
    ]
