# Generated by Django 5.0.6 on 2024-08-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_imagecar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsVip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Vip')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='Vip'),
        ),
    ]
