# Generated by Django 5.0.6 on 2024-08-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_profile_email_profile_name_profile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='username',
        ),
    ]
