# Generated by Django 5.0.6 on 2024-08-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_profile_email_remove_profile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=11, max_length=16),
            preserve_default=False,
        ),
    ]
