# Generated by Django 5.0.6 on 2024-08-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Yaradılma vaxtı'),
        ),
        migrations.AddField(
            model_name='car',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Baxış sayı'),
        ),
    ]
