# Generated by Django 5.0.4 on 2024-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_remove_profile_email_remove_profile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitmə vaxtı'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaradılma vaxtı'),
        ),
    ]
